colors:
  bg: "1e2030"              # #1e2030
  fg: "c8d3f5"              # #c8d3f5
  black1: "252d53"          # #252d53
  black: "444a73"           # #444a73
  blue: "2090ff"            # #2090ff
  bright_black: "4f6490"    # #4f6490
  bright_blue: "8494FF"     # #8494FF
  bright_cyan: "1abc9c"     # #1abc9c
  bright_green: "85c55a"    # #85c55a
  bright_magenta: "7070ff"  # #7070ff
  bright_red: "f070a8"      # #f070a8
  bright_white: "e8e8e8"    # #e8e8e8
  bright_yellow: "f0c000"   # #ffaa00
  browngray: "bfb49f"       #'#bfb09f'
  cyan: "0d7a8f"            # #0d7a8f
  gray: "40495d"            # #40495d
  green: "7acc35"           # #7acc35
  magenta: "8052d4"         # #8052d4
  orange: "ff8000"          # #ff8000
  red: "ea1479"             # #ea1479
  white: "969ac9"           # #969ac9
  yellow: "ffaa00"          # #ffcc00

  # blue: "0083f7"            # #0083f7
  # bright_black: "465a82"    # #465a82
  # bright_magenta: "A59BFF"  # #A59BFF
  # bright_red: "f47cb4"      # #f47cb4
  # bright_white: "e9e9ec"    # #e9e9e9
  # bright_green: "9ece6a"    # #9ece6a
  # green: "8fd742"           # #8fd742
  # magenta: "6f42c1"         # #6f42c1
  # cyan: "8494FF"            # #8494FF

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}
  multi_hard_link: {}

  directory:
    foreground: bright_blue

  symlink:
    foreground: bright_magenta
    font-style: underline

  fifo:
    foreground: black
    background: cyan

  socket:
    foreground: black
    background: bright_red

  door:
    foreground: black
    background: bright_red

  block_device:
    foreground: cyan
    background: black1

  character_device:
    foreground: red
    background: black1

  broken_symlink:
    foreground: black
    background: red

  missing_symlink_target:
    foreground: black
    background: red

  setuid: {}

  setgid: {}

  file_with_capability: {}

  sticky_other_writable: {}

  other_writable: {}

  sticky: {}

  executable_file:
    foreground: bright_red
    font-style: bold

text:
  special:
    foreground: bg
    background: fg

  todo:
    foreground: red
    font-style: underline

  licenses:
    foreground: gray

  configuration:
    foreground: bright_blue
    font-style: underline

  other:
    foreground: bright_yellow

markup:
  foreground: bright_blue

programming:
  source:
    foreground: cyan

  project:
    dotfiles:
      foreground: green

    environment:
      foreground: yellow

    tooling:
      testing:
        foreground: green
        font-style: underline
      analysis:
        foreground: bright_magenta
        font-style: underline
      style:
        foreground: bright_magenta
        font-style: underline
      output:
        foreground: white

    ignore:
      foreground: magenta

    dependencies:
      config:
        foreground: red
        font-style: underline

      secondary:
        foreground: red

  tooling:
    foreground: bright_magenta

    documentation:
      project:
        background: fg
        foreground: bg

      doxygen:
        background: fg
        foreground: bg

    continuous-integration:
      foreground: yellow

media:
  foreground: orange

office:
  foreground: bright_blue

archives:
  foreground: bright_red
  font-style: underline

executable:
  foreground: bright_red
  font-style: bold

unimportant:
  foreground: white
