gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor: ["#ff8000", bold]
    inactiveBorderColor: [default]
    searchingActiveBorderColor: ["#ff8000", bold]
    optionsTextColor: [blue]
    selectedLineBgColor: [blue]
    inactiveViewSelectedLineBgColor: [bold]
    cherryPickedCommitFgColor: [blue]
    cherryPickedCommitBgColor: [cyan]
    markedBaseCommitFgColor: [blue]
    markedBaseCommitBgColor: [yellow]
    unstagedChangesColor: [red]
    defaultFgColor: [default]
git:
  pagers:
    - colorArg: always
      # pager: delta --detect-dark-light=always --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      pager: delta --detect-dark-light=always --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
