[tools]
"npm:neovim" = "latest"
"npm:ocx" = "latest"
"npm:opensrc" = "latest"
"npm:skills" = "latest"
"npm:taze" = "latest"
bun = "latest"
node = "lts"
usage = "latest"

[settings]
# cargo_binstall = true
# trusted_config_paths = ["~/.development/Projects/"]
idiomatic_version_file_enable_tools = ["node"]
